ARDUINODIR:=/Applications/Arduino.marlin.app/Contents/Resources/Java
AVRTOOLSPATH := $(ARDUINODIR)/hardware/tools/avr/bin
SOURCES := oled_demo.ino 
LIBRARIES := SPI oled256
BOARD := mighty_opt
#BOARD := atmega328


include arduino.mk
