/* CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at src/license_cddl-1.0.txt
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at src/license_cddl-1.0.txt
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/* Copyright (c) 2014, Michael Neiderhauser. All rights reserved. */

/*!  \file     flash_test.h
*    \brief    Mooltipass Node Test Functions Header
*    Created:  2/5/2014
*    Author:   Michael Neiderhauser
*/

#ifndef NODE_TEST_H_
#define NODE_TEST_H_

#include "defines.h"
#include "node_mgmt.h"
#include <stdint.h>

/*!
*  Parent Node Test Error Codes ENUM
*/
typedef enum
{
    /* -------------------------- INIT -------------------------------------*/
    PARENT_NODE_TEST_PARENT_NODE_AOK = 0,
    PARENT_NODE_TEST_ERASE_ALL_SECTORS_ERROR,
    PARENT_NODE_TEST_INIT_HANDLE_FUNCTION_FAIL,
    PARENT_NODE_TEST_USER_PROFILE_SET_START_NULL_ERROR,
    PARENT_NODE_TEST_USER_PROFILE_CLEAR_FAV_ERROR,
    PARENT_NODE_TEST_HANDLE_UID_ERROR, // 5
    PARENT_NODE_TEST_HANDLE_FIRST_PARENT_NODE_ERROR,
    PARENT_NODE_TEST_HANDLE_FREE_PARENT_NODE_ERROR,
    /* -------------------------- STEP 1 -------------------------------------*/
    PARENT_NODE_TEST_STEP_1_CREATE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_1_CREATE_NODE_VERIFY_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_1_CREATE_NODE_VERIFY_NEXT_NODE_ERROR, // 10
    PARENT_NODE_TEST_STEP_1_CREATE_NODE_VERIFY_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_1_VERIFY_HANDLE_FIRST_NODE_ERROR,
    PARENT_NODE_TEST_STEP_1_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR,
    /* -------------------------- STEP 2 -------------------------------------*/
    PARENT_NODE_TEST_STEP_2_CREATE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_2_CREATE_NODE_VERIFY_SERVICE_ERROR, // 15
    PARENT_NODE_TEST_STEP_2_CREATE_NODE_VERIFY_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_2_CREATE_NODE_VERIFY_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_2_READ_NODE_C_ERROR,
    PARENT_NODE_TEST_STEP_2_VERIFY_NODE_C_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_2_VERIFY_NODE_C_NEXT_NODE_ERROR, // 20
    PARENT_NODE_TEST_STEP_2_VERIFY_NODE_C_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_2_VERIFY_HANDLE_FIRST_NODE_ERROR,
    PARENT_NODE_TEST_STEP_2_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR,
    /* -------------------------- STEP 3 -------------------------------------*/
    PARENT_NODE_TEST_STEP_3_CREATE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_3_CREATE_NODE_VERIFY_SERVICE_ERROR, // 25
    PARENT_NODE_TEST_STEP_3_CREATE_NODE_VERIFY_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_3_CREATE_NODE_VERIFY_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_3_READ_NODE_C_ERROR,
    PARENT_NODE_TEST_STEP_3_VERIFY_NODE_C_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_3_VERIFY_NODE_C_NEXT_NODE_ERROR, // 30
    PARENT_NODE_TEST_STEP_3_VERIFY_NODE_C_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_3_READ_NODE_M_ERROR,
    PARENT_NODE_TEST_STEP_3_VERIFY_NODE_M_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_3_VERIFY_NODE_M_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_3_VERIFY_NODE_M_PREV_NODE_ERROR, // 35
    PARENT_NODE_TEST_STEP_3_VERIFY_HANDLE_FIRST_NODE_ERROR,
    PARENT_NODE_TEST_STEP_3_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR,
    /* -------------------------- STEP 4 -------------------------------------*/
    PARENT_NODE_TEST_STEP_4_CREATE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_CREATE_NODE_VERIFY_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_4_CREATE_NODE_VERIFY_NEXT_NODE_ERROR, // 40
    PARENT_NODE_TEST_STEP_4_CREATE_NODE_VERIFY_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_READ_NODE_C_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_C_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_C_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_C_PREV_NODE_ERROR, // 45
    PARENT_NODE_TEST_STEP_4_READ_NODE_K_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_K_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_K_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_K_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_READ_NODE_M_ERROR, // 50
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_M_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_M_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_NODE_M_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_HANDLE_FIRST_NODE_ERROR,
    PARENT_NODE_TEST_STEP_4_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR, // 55
    /* -------------------------- STEP 5 -------------------------------------*/
    PARENT_NODE_TEST_STEP_5_DELETE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_5_READ_NODE_A_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_A_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_A_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_A_PREV_NODE_ERROR, // 60
    PARENT_NODE_TEST_STEP_5_READ_NODE_C_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_C_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_C_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_C_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_5_READ_NODE_M_ERROR, // 65
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_M_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_M_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_NODE_M_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_HANDLE_FIRST_NODE_ERROR,
    PARENT_NODE_TEST_STEP_5_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR, // 70
    /* -------------------------- STEP 6 -------------------------------------*/
    PARENT_NODE_TEST_STEP_6_DELETE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_6_READ_NODE_A_ERROR,
    PARENT_NODE_TEST_STEP_6_VERIFY_NODE_A_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_6_VERIFY_NODE_A_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_6_VERIFY_NODE_A_PREV_NODE_ERROR, // 75
    PARENT_NODE_TEST_STEP_6_READ_NODE_C_ERROR,
    PARENT_NODE_TEST_STEP_6_VERIFY_NODE_C_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_6_VERIFY_NODE_C_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_6_VERIFY_NODE_C_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_6_VERIFY_HANDLE_FIRST_NODE_ERROR, // 80
    PARENT_NODE_TEST_STEP_6_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR,
    /* -------------------------- STEP 7 -------------------------------------*/
    PARENT_NODE_TEST_STEP_7_DELETE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_7_READ_NODE_C_ERROR,
    PARENT_NODE_TEST_STEP_7_VERIFY_NODE_C_SERVICE_ERROR,
    PARENT_NODE_TEST_STEP_7_VERIFY_NODE_C_NEXT_NODE_ERROR, // 85
    PARENT_NODE_TEST_STEP_7_VERIFY_NODE_C_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_7_VERIFY_HANDLE_FIRST_NODE_ERROR,
    PARENT_NODE_TEST_STEP_7_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR,
    /* -------------------------- STEP 8 -------------------------------------*/
    PARENT_NODE_TEST_STEP_8_DELETE_NODE_ERROR,
    PARENT_NODE_TEST_STEP_8_VERIFY_HANDLE_FIRST_NODE_ERROR, // 90
    PARENT_NODE_TEST_STEP_8_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR,
    /* -------------------------- STEP 9 -------------------------------------*/
    PARENT_NODE_TEST_STEP_9_CREATE_NODE_B_ERROR,
    PARENT_NODE_TEST_STEP_9_CREATE_NODE_A_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_HANDLE_FIRST_NODE_1_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_HANDLE_NEXT_FREE_NODE_1_ERROR, // 95
    PARENT_NODE_TEST_STEP_9_UPDATE_NODE_A_1_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_HANDLE_FIRST_NODE_2_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_HANDLE_NEXT_FREE_NODE_2_ERROR,
    PARENT_NODE_TEST_STEP_9_UPDATE_NODE_A_2_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_NODE_C_SERVICE_ERROR, // 100
    PARENT_NODE_TEST_STEP_9_VERIFY_NODE_C_NEXT_NODE_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_NODE_C_PREV_NODE_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_HANDLE_FIRST_NODE_3_ERROR,
    PARENT_NODE_TEST_STEP_9_VERIFY_HANDLE_NEXT_FREE_NODE_3_ERROR, //104
} parentNodeTestError;

/*!
*  Child Node Test Error Codes ENUM
*/
typedef enum
{
    /* -------------------------- INIT -------------------------------------*/
    CHILD_NODE_TEST_AOK = 0,
    CHILD_NODE_TEST_FORMAT_FLASH_FAIL,
    CHILD_NODE_TEST_FORMAT_USER_PROFILE_FAIL,
    CHILD_NODE_TEST_INIT_HANDLE_FUNCTION_FAIL,
    CHILD_NODE_TEST_USER_PROFILE_SET_START_NULL_ERROR,
    CHILD_NODE_TEST_HANDLE_UID_ERROR, //5
    CHILD_NODE_TEST_HANDLE_FIRST_PARENT_NODE_ERROR,
    CHILD_NODE_TEST_HANDLE_FREE_PARENT_NODE_ERROR,
    CHILD_NODE_TEST_HANDLE_FREE_CHILD_NODE_ERROR,
    /* -------------------------- STEP 0 -------------------------------------*/
    CHILD_NODE_TEST_STEP_0_CREATE_PARENT_NODE_ERROR,
    CHILD_NODE_TEST_STEP_0_CREATE_PARENT_NODE_VERIFY_SERVICE_ERROR, // 10
    CHILD_NODE_TEST_STEP_0_CREATE_PARENT_NODE_VERIFY_NEXT_NODE_ERROR,
    CHILD_NODE_TEST_STEP_0_CREATE_PARENT_NODE_VERIFY_PREV_NODE_ERROR,
    CHILD_NODE_TEST_STEP_0_CREATE_PARENT_NODE_VERIFY_HANDLE_FIRST_NODE_ERROR,
    CHILD_NODE_TEST_STEP_0_CREATE_PARENT_NODE_VERIFY_HANDLE_NEXT_FREE_NODE_ERROR,
    /* -------------------------- STEP 1 -------------------------------------*/
    CHILD_NODE_TEST_STEP_1_READ_PARENT_START_ERROR, // 15
    CHILD_NODE_TEST_STEP_1_CREATE_CHILD_NODE_ERROR,
    CHILD_NODE_TEST_STEP_1_READ_CHILD_NODE_A_ERROR,
    CHILD_NODE_TEST_STEP_1_VERIFY_CHILD_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_1_VERIFY_CHILD_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_1_VERIFY_CHILD_LOGIN_DATA_ERROR, // 20
    CHILD_NODE_TEST_STEP_1_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_1_VERIFY_PARENT_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_1_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 2 -------------------------------------*/
    CHILD_NODE_TEST_STEP_2_READ_PARENT_START_ERROR,
    CHILD_NODE_TEST_STEP_2_CREATE_CHILD_NODE_ERROR, // 25
    CHILD_NODE_TEST_STEP_2_READ_CHILD_NODE_M_ERROR,
    CHILD_NODE_TEST_STEP_2_VERIFY_CHILD_M_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_2_VERIFY_CHILD_M_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_2_VERIFY_CHILD_M_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_2_READ_CHILD_NODE_C_ERROR, //30
    CHILD_NODE_TEST_STEP_2_VERIFY_CHILD_C_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_2_VERIFY_CHILD_C_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_2_VERIFY_CHILD_C_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_2_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_2_VERIFY_PARENT_NEXT_CHILD_ERROR, // 35
    CHILD_NODE_TEST_STEP_2_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 3 -------------------------------------*/
    CHILD_NODE_TEST_STEP_3_READ_PARENT_START_ERROR,
    CHILD_NODE_TEST_STEP_3_CREATE_CHILD_NODE_ERROR,
    CHILD_NODE_TEST_STEP_3_READ_CHILD_NODE_K_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_K_NEXT_CHILD_ERROR, // 40
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_K_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_K_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_3_READ_CHILD_NODE_M_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_M_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_M_PREV_CHILD_ERROR, //45
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_M_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_3_READ_CHILD_NODE_C_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_C_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_C_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_CHILD_C_LOGIN_DATA_ERROR, //50
    CHILD_NODE_TEST_STEP_3_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_PARENT_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_3_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 4 -------------------------------------*/
    CHILD_NODE_TEST_STEP_4_READ_PARENT_START_ERROR,
    CHILD_NODE_TEST_STEP_4_CREATE_CHILD_NODE_ERROR, // 55
    CHILD_NODE_TEST_STEP_4_READ_CHILD_NODE_A_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_A_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_A_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_A_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_4_READ_CHILD_NODE_K_ERROR, // 60
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_K_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_K_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_K_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_4_READ_CHILD_NODE_M_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_M_NEXT_CHILD_ERROR, // 65
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_M_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_M_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_4_READ_CHILD_NODE_C_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_C_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_C_PREV_CHILD_ERROR, //70
    CHILD_NODE_TEST_STEP_4_VERIFY_CHILD_C_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_4_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_PARENT_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_4_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 5 -------------------------------------*/
    CHILD_NODE_TEST_STEP_5_READ_PARENT_START_ERROR, // 75
    CHILD_NODE_TEST_STEP_5_DELETE_CHILD_NODE_ERROR,
    CHILD_NODE_TEST_STEP_5_READ_CHILD_NODE_A_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_A_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_A_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_A_LOGIN_DATA_ERROR, // 80
    CHILD_NODE_TEST_STEP_5_READ_CHILD_NODE_M_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_M_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_M_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_M_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_5_READ_CHILD_NODE_C_ERROR, // 85
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_C_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_C_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_CHILD_C_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_5_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_5_VERIFY_PARENT_NEXT_CHILD_ERROR, // 90
    CHILD_NODE_TEST_STEP_5_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 6 -------------------------------------*/
    CHILD_NODE_TEST_STEP_6_READ_PARENT_START_ERROR,
    CHILD_NODE_TEST_STEP_6_DELETE_CHILD_NODE_ERROR,
    CHILD_NODE_TEST_STEP_6_READ_CHILD_NODE_A_ERROR,
    CHILD_NODE_TEST_STEP_6_VERIFY_CHILD_A_NEXT_CHILD_ERROR, //95
    CHILD_NODE_TEST_STEP_6_VERIFY_CHILD_A_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_6_VERIFY_CHILD_A_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_6_READ_CHILD_NODE_C_ERROR,
    CHILD_NODE_TEST_STEP_6_VERIFY_CHILD_C_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_6_VERIFY_CHILD_C_PREV_CHILD_ERROR, // 100
    CHILD_NODE_TEST_STEP_6_VERIFY_CHILD_C_LOGIN_DATA_ERROR,
    CHILD_NODE_TEST_STEP_6_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_6_VERIFY_PARENT_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_6_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 7 -------------------------------------*/
    CHILD_NODE_TEST_STEP_7_READ_PARENT_START_ERROR, // 105
    CHILD_NODE_TEST_STEP_7_DELETE_CHILD_NODE_ERROR,
    CHILD_NODE_TEST_STEP_7_READ_CHILD_NODE_C_ERROR,
    CHILD_NODE_TEST_STEP_7_VERIFY_CHILD_C_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_7_VERIFY_CHILD_C_PREV_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_7_VERIFY_CHILD_C_LOGIN_DATA_ERROR, // 110
    CHILD_NODE_TEST_STEP_7_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_7_VERIFY_PARENT_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_7_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 8 -------------------------------------*/
    CHILD_NODE_TEST_STEP_8_READ_PARENT_START_ERROR,
    CHILD_NODE_TEST_STEP_8_DELETE_CHILD_NODE_ERROR, // 115
    CHILD_NODE_TEST_STEP_8_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_8_VERIFY_PARENT_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_8_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    /* -------------------------- STEP 9 -------------------------------------*/
    CHILD_NODE_TEST_STEP_9_READ_PARENT_START_ERROR,
    CHILD_NODE_TEST_STEP_9_CREATE_CHILD_NODE_B_ERROR, //120
    CHILD_NODE_TEST_STEP_9_CREATE_CHILD_NODE_A_ERROR,
    CHILD_NODE_TEST_STEP_9_READ_PARENT_END_ERROR,
    CHILD_NODE_TEST_STEP_9_VERIFY_PARENT_NEXT_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_9_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR,
    CHILD_NODE_TEST_STEP_9_READ_CHILD_NODE_A_ERROR, // 125
    CHILD_NODE_TEST_STEP_9_UPDATE_CHILD_NODE_A_ERROR,
    CHILD_NODE_TEST_STEP_9_READ_PARENT_END_ERROR_2,
    CHILD_NODE_TEST_STEP_9_VERIFY_PARENT_NEXT_CHILD_ERROR_2,
    CHILD_NODE_TEST_STEP_9_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR_2,
    CHILD_NODE_TEST_STEP_9_READ_CHILD_NODE_A_ERROR_2, // 130
    CHILD_NODE_TEST_STEP_9_UPDATE_CHILD_NODE_A_C_ERROR_2,
    CHILD_NODE_TEST_STEP_9_READ_PARENT_END_ERROR_3,
    CHILD_NODE_TEST_STEP_9_VERIFY_PARENT_NEXT_CHILD_ERROR_3,
    CHILD_NODE_TEST_STEP_9_VERIFY_HANDLE_NEXT_FREE_CHILD_ERROR_3
    
} childNodeTestError;

RET_TYPE nodeTest();
RET_TYPE nodeFlagFunctionTest();
RET_TYPE nodeAddressTest();
RET_TYPE userProfileOffsetTest();
RET_TYPE nodeInitHandle();
RET_TYPE userProfileAddressTest(mgmtHandle *h);
void printParentNode(pNode *p);
RET_TYPE parentNodeTest(mgmtHandle *h, uint8_t *code);
RET_TYPE childNodeTest(mgmtHandle *h, uint8_t *code);


#endif /* FLASH_TEST_H_ */